### PR TITLE
Issue #88: Fix user registration bugs in deployed environments

### LINKED ISSUE #88: [BUG] Front-end cannot access back-end server due to different hostnames
### Description

When front-end & back-end have different hostnames, front-end would not be able to access to back-end unless we're using `cors`. For more details, see [Access to XMLHttpRequest at '...' from origin 'localhost:3000' has been blocked by CORS policy](https://stackoverflow.com/a/63734701).

Screen Shot 2021-02-23 at 7 36 35 PM

### Expected Results
No error when registering new user.

### Actual Results
The following error pops up: 
`Access to XMLHttpRequest at 'https://rentr-dev.herokuapp.com/api/v1/user/registration' from origin 'https://rentr-front-end.herokuapp.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

### Additional Notes
The first error, `ERR_CONNECTION_REFUSED`, is due to the hardcoded testing url from the frontend. This issue would not be fixing that error.

### PR DESCRIPTION
**Pull request by jcsnorlax97**
### Associated Issues:
- User Stories: N/A
- Dev Tasks: #88

### Description

After deploying the backend and the frontend into Heroku, we found that we weren't not able to register new users due to:
1. `Access to XMLHttpRequest at 'https://rentr-dev.herokuapp.com/api/v1/user/registration' from origin 'https://rentr-front-end.herokuapp.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
2. `500 Internal Error`

Based on investigation, the first error is because we are calling back-end server from another domain name, i.e. calling server domain, `https://rentr-dev.herokuapp.com`, from client domain `https://rentr-front-end.herokuapp.com/`. This can be resolved by adding the `cors` middleware in the `app.js` such that this is called before each route is called.

As for the `500 Internal Error`, after some investigations & debugging locally, the error refers to `"error: value too long for type character varying(50)"` happening in the DAO layer when doing queries to the database. This is resolved by changing the `password` constraint from `VARCHAR(500)` to `VARCHAR CHECK (length(password) <= 500)` in the SQL script for initializing the database.

In addition to these two bug fixing, the following places have also been updated:
- `VARCHAR(...)` constraints in `rentr_listing` table found from the SQL script, for consistency.
- 500 error message in `api-error-handler.js` such that it helps users or devs to debug easier.
- pre-controller password maximum length validation - setting 100 characters to be maximum just in case of "naughty" users.

### Main References
- [Access to XMLHttpRequest at '…' from origin 'localhost:3000' has been blocked by CORS policy](https://stackoverflow.com/a/63734701)
- [MDN Web Docs - Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
- [Strange PostgreSQL “value too long for type character varying(500)”](https://stackoverflow.com/questions/13485030/strange-postgresql-value-too-long-for-type-character-varying500)

### Output Screenshot

- Before:
Screen Shot 2021-02-23 at 7 36 35 PM

- After (UI):
Screen Shot 2021-02-24 at 2 26 57 AM

- After (DB):
Screen Shot 2021-02-24 at 1 40 49 AM

### Time spent
- 5h

### Github action
close #88

### CODE REVIEW

File: server/migrations/init.sql [hunk 1]
```diff
@@ -11,24 +11,24 @@ CREATE EXTENSION citext;
...
+    password VARCHAR CHECK (length(password) <= 100) NOT NULL
 );
 
 INSERT INTO rentr_user(email, password) VALUES 
-('bosco@gmail.com', 'bosco123'),
-('justin@gmail.com', 'justin123'),
-('ronnie@gmail.com', 'ronnie123'),
-('azizul@gmail.com', 'azizul123'),
-('nathan@gmail.com', 'nathan123');
+('bosco@gmail.com', '$2b$10$b8/KshrtCRlab2qos7M1zO8cbAB7G4bB3RsN7bH8b21L9YiKbc51G'),
```
Comment (NathanCarriere) [inline server/migrations/init.sql:18]: Are these changes related?

**Review by NathanCarriere — APPROVED** [review]

File: server/migrations/init.sql (hunk 1 above)
Comment (jcsnorlax97) [reply server/migrations/init.sql:18]: @NathanCarriere May not be related. But as we're storing the encrypted password having > 6 characters in the `/user/registration` POST API endpoint, this is just trying to ensure the data stored in the DB matches the constraints.

**Review by AzizulHakim96 — APPROVED** [review]

File: server/migrations/init.sql [hunk 2]
```diff
@@ -11,24 +11,24 @@ CREATE EXTENSION citext;
 CREATE TABLE IF NOT EXISTS rentr_user (
     id SERIAL PRIMARY KEY,
     email CITEXT UNIQUE NOT NULL,
-    password VARCHAR(500) NOT NULL
+    password VARCHAR CHECK (length(password) <= 100) NOT NULL
```
Comment (RonnieDsouza) [inline server/migrations/init.sql:14]: I'm guessing you tested that the hashes are less than 100 chars so we don't need it to be 500? Looks good otherwise!

**Review by RonnieDsouza — APPROVED** [review]

File: server/migrations/init.sql (hunk 2 above)
Comment (jcsnorlax97) [reply server/migrations/init.sql:14]: Yeah. The encrypted password is 60 characters. Extra 40 characters are just in case the package updates itself and changes the output length after the encryption.
